# Generated by Django 6.0.7 on 2026-08-26 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlanningData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200)),
                ('estimated_cost', models.CharField(max_length=200)),
                ('soil_information', models.TextField()),
                ('required_permissions', models.TextField()),
            ],
        ),
    ]
