# Generated by Django 6.0.7 on 2026-08-27 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoringData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_stage', models.CharField(max_length=100)),
                ('current_status', models.CharField(max_length=200)),
                ('progress', models.IntegerField(default=0)),
                ('planning_completed', models.BooleanField(default=True)),
                ('site_preparation_completed', models.BooleanField(default=False)),
                ('foundation_in_progress', models.BooleanField(default=False)),
                ('structural_work_completed', models.BooleanField(default=False)),
                ('final_inspection_completed', models.BooleanField(default=False)),
            ],
        ),
    ]
