# Generated by Django 6.0.7 on 2026-08-29 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_monitoringdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstructionProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_stage', models.CharField(max_length=200)),
                ('current_status', models.CharField(max_length=200)),
                ('progress', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
