# Generated by Django 6.0.7 on 2026-08-29 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_constructionprogress'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrackDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='crack_images/')),
                ('result', models.CharField(max_length=200)),
                ('confidence', models.FloatField(default=0)),
                ('crack_count', models.IntegerField(default=0)),
                ('severity', models.CharField(max_length=100)),
                ('recommendation', models.TextField()),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
